### PR TITLE
failing test with []int

### PR DESCRIPTION
**Pull request by ineiti**
Adds two tests with regard to ints:
- slice of int
- pointer to int

### CODE REVIEW

**Comment by ineiti** [comment]
Should be tested against latest protobuf as Ismail worked on the en/decoding of slices.

**Comment by Liamsi** [comment]
> Should be tested against latest protobuf as Ismail worked on the en/decoding of slices.

I don't think my changes would resolve this issue. They were only related to map (or maps with arrays as values).

**Comment by ineiti** [comment]
And here we have the problem of what to do with `int` - should it be encoded as 32 or 64-bit value? What if `size(int)` is different on the sender or the receiver?

**Comment by marco709394** [comment]
Just curious, why not just treat int slice as int64 like you do the case of int32 ?
Please ignore me if it is no longer an issue or you have other consideration :)

**Comment by Liamsi** [comment]
> Just curious, why not just treat int slice as int64 like you do the case of int32 ?
> Please ignore me if it is no longer an issue or you have other consideration :)

It's still an issue. If you have time we are happy about a PR. If not, we will take care of that issue soon, anyways.

**Comment by Liamsi** [comment]
@marco709394 added a PR realted to this issue: #28

**Comment by ineiti** [comment]
Look at the PR from @Liamsi and see if we can include it.

**Comment by ineiti** [comment]
Superseded by #42

**Pull request closed without merging**
