### PR TITLE
Print the actual error message instead of an index-out-of-range

### PR DESCRIPTION
**Pull request by Liamsi**
Alternative solution for issue #18 
Please review carefully. Maybe these changes have some side-effects I missed while listening on how-to scale block-chains at SuRi ;-)

### CODE REVIEW

**Comment by ineiti** [comment]
I still think that the `protobuf` should return an error if the buffer given to decode is too big. I ran into this a couple of times and would've *loved* a good error-return.

**Comment by Liamsi** [comment]
> I still think that the protobuf should return an error if the buffer given to decode is too big. I ran into this a couple of times and would've loved a good error-return.

What do you mean by too big? There is no size limit in the buffer... The problem you mentioned in the issue (the error doesn't get shown but index-out-of-bound) doesn't occur anymore.

**Comment by ineiti** [comment]
Something like #22

**Comment by Liamsi** [comment]
> Something like #22

OK, I see what you want. Also thought about this but I wasn't sure if it is an actual error if the buffer isn't completely used. I checked against the original protobuf lib and it doesn't seem to behave like this (it throws an error if the buffer is to short, though)

**Comment by Liamsi** [comment]
Closing this one as discussed with @ineiti

**Pull request closed without merging**
